export default {
  functions: {
    directory: 'node-functions',
  },

  build: {
    external: [
      'fs',
      'path',
      'crypto',
      'http',
      'https',
      'net',
      'tls',
      'stream',
      'url',
      'util',
      'zlib',
      'timers',
      'os',
      'events',
      'buffer',
      'querystring',
      'string_decoder',
      'punycode',

      'fs/promises',
      'stream/promises',
      'stream/web',
      'node:fs',
      'node:path',
      'node:crypto',
      'node:http',
      'node:https',
      'node:stream',
      'node:url',
      'node:os',
      'node:net',
      'node:tls',
      'node:util',
      'node:zlib',
      'node:timers',
      'node:events',
      'node:buffer',
      'node:querystring',

      'better-sqlite3',
      'mysql2',
      'pg',
      'jsonwebtoken',
      '@tursodatabase/serverless',
    ],
  },
};
